### PR TITLE
Added features and improved the source code

### PR DESCRIPTION
**Pull request by alexandrampalliou**
Hello, 
Happy new year, I hope this email finds you well. My name is Alexandra Mpalliou and I am an undergraduate student at the Computer Science Department in Aristotle University of Thessaloniki. This semester, I'm attending a Software Engineering class in which I have been assigned to extend to my liking an open source program. I have chosen your  Calculator- AWT project and I have added a few extra functions like the backspace and the power operator as well as the ability to calculate square root and module with the according input error check.  In the uploaded file you can see the edited code, I'd really appreciate it if you could add it to your code.
[calc_AWT_ext.zip](https://github.com/FahimFBA/Calculator-AWT/files/10473095/calc_AWT_ext.zip)

### CODE REVIEW

**Comment by Vyvy-vi** [comment]
Hey @alexandrampalliou, Welcome to the Calculator-AWT project!
It seems like your branch is out-dated and is trying to push older changes into the project. Could you rebase your PR to the latest version of the `main` branch?
Also, it seems like your changes aren't visible here, perhaps they weren't committed?

**Comment by FahimFBA** [comment]
Thank you @alexandrampalliou for the changes, but please try to rebase the PR according to @Vyvy-vi. 
Also, this button actually does not work. Can you please check it out again?
image

**Comment by alexandrampalliou** [comment]
Hello, sorry for being a little late. Here is the updated code. I had a problem with Button and the backspace symbol couldn't be recognised ,so i used Jbutton. If you don't fancy this verison I can bring back Button and change the label to "BACKSPACE". What do you think?
[calcAWT_ext.zip](https://github.com/FahimFBA/Calculator-AWT/files/10494468/calcAWT_ext.zip)

**Comment by FahimFBA** [comment]
Thanks, @alexandrampalliou for the continuous contribution!
Let me change this version real quick. 😊

**Comment by FahimFBA** [comment]
Hello @alexandrampalliou, I have checked your last code, and that is looking great! If I push the code in the main codebase, then GitHub won't show you as a contributor. 

If you face a problem rebasing the repo, then can you please delete your previous repository, fork this repository again, add the changes and create another pull request?

In that way, you will not face any merge conflicts or complications anymore. 

Please let me know what do you think about this. I am always ready to help! :)

**Pull request closed without merging**
